---
apiVersion: v1
kind: Service
metadata:
 name: nginx
spec:
 type: NodePort
 ports:
   - name: http
     port: 80
     nodePort: 30080
   - name: https
     port: 443
     nodePort: 30443
 selector:
   app: nginx
---
apiVersion: v1
kind: Service
metadata:
 name: jenkinsapp
spec:
 type: NodePort
 ports:
   - name: jenkins-http
     port: 8080
     nodePort: 30555
   - name: jenkins-https
     port: 8443
     nodePort: 30444
   - name: jenkins-agent
     port: 50000
 selector:
   app: jenkinsapp
---
apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
   app: nginx
spec:
 volumes:
 - name: nginxconf
   hostPath:
     path: /mnt/nginx_conf
 - name: nginx-conf
   configMap:
     name: nginx-conf
 containers:
 - name: nginx
   image: toru2220/nginx
   volumeMounts:
   - name: nginxconf
     mountPath: /etc/nginx/conf.d
   - name: nginx-conf
     mountPath: /etc/nginx/nginx.conf
     subPath: nginx.conf
   resources:
     requests:
       memory: "128Mi"
       cpu: "250m"
     limits:
       memory: "256Mi"
       cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
 name: jenkinsapp
 labels:
   app: jenkinsapp
spec:
 volumes:
 - name: jenkinsdata
   hostPath:
     path: /var/jenkins_home
 containers:
 - name: jenkins
   image: jenkins/jenkins:jdk11
   ports:
     - name: https
       containerPort: 8443
     - name: http
       containerPort: 8080
     - name: slaveport
       containerPort: 50000
   volumeMounts:
     - mountPath: /var/jenkins_home
       name: jenkinsdata
   env:
     - name: JENKINS_OPTS
       value: --httpPort=8080 --httpsPort=8443 --prefix=/jenkins
     - name: JAVA_OPTS
       value: -Duser.timezone=Asia/Tokyo
   resources:
     requests:
       memory: "2048Mi"
       cpu: "1000m"
     limits:
       memory: "4096Mi"
       cpu: "2000m"
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-conf
data:
 nginx.conf: |-
   user  nginx;
   worker_processes  1;
   error_log  /var/log/nginx/error.log warn;
   pid        /var/run/nginx.pid;
   events {
       worker_connections  1024;
   }
   http {
       include       /etc/nginx/mime.types;
       default_type  application/octet-stream;
       sendfile        on;
       keepalive_timeout  65;
       #include /etc/nginx/conf.d/*.conf;
       server {
         listen 80;
         #server_name donaishitanyarobert.mydns.jp;
         location /jenkins {
           proxy_pass              http://jenkinsapp:8080/jenkins;
           proxy_redirect          default;
           proxy_set_header        Host $host:$server_port;
           proxy_set_header        X-Real-IP $remote_addr;
           proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header        X-Forwarded-Proto $scheme;
         }
       }
       server {
         listen 443 ssl;
         server_name donaishitanyarobert.mydns.jp;
         ssl_certificate /etc/nginx/conf.d/fullchain.pem;
         ssl_certificate_key /etc/nginx/conf.d/privkey.pem;
         ssl_session_timeout 5m;
         ssl_protocols TLSv1; ssl_ciphers
         ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
         ssl_prefer_server_ciphers on;
         location /jenkins {
           proxy_pass              https://jenkinsapp:8443/jenkins;
           proxy_redirect          http:// https://;
           proxy_set_header        Host $host:$server_port;
           proxy_set_header        X-Real-IP $remote_addr;
           proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header        X-Forwarded-Proto $scheme;
         }
       }
   }
